apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: client-app
        version: v1
    spec:
      containers:
      - name: client-app
        image: <amazonecrfullimagename>
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client-app
  labels:
    app: client-app
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: client-app
  type: LoadBalancer
